name: Downgraded Release

on:
    push:
        tags:
            # avoid infinite looping, skip tags that ends with ".74"
            # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-branches
            - '*'

jobs:
    downgrade_release:
        runs-on: ubuntu-latest

        steps:
            -   uses: "actions/checkout@v3"
                with:
                    token: ${{ secrets.WORKFLOWS_TOKEN }}

            -
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: 8.4
                    coverage: none

            # invoke patches
            -   run: composer install --ansi

            # but no dev packages
            -   run: composer update --no-dev --ansi

            # get rector to "rector-local" directory, to avoid downgrading itself in the /vendor
            -   run: mkdir rector-local
            -   run: composer require rector/rector --working-dir rector-local --ansi

            # downgrade to PHP 7.4
            -   run: rector-local/vendor/bin/rector process bin src vendor --config build/rector-downgrade-php.php --ansi

            # clear the dev files
            -   run: rm -rf tests ecs.php phpstan.neon phpunit.xml .gitignore .editorconfig

            # prefix and scope
            -
                name: "Prefix and scope code"
                run: |
                    # inspired from https://github.com/rectorphp/rector/blob/main/build/build-rector-scoped.sh

                    # see https://stackoverflow.com/questions/66644233/how-to-propagate-colors-from-bash-script-to-github-action?noredirect=1#comment117811853_66644233
                    export TERM=xterm-color

                    # show errors
                    set -e

                    # script fails if trying to access to an undefined variable
                    set -u

                    # functions
                    note()
                    {
                        MESSAGE=$1;
                        printf "\n";
                        echo "\033[0;33m[NOTE] $MESSAGE\033[0m";
                    }

                    # ---------------------------

                    # 2. scope it
                    note "Downloading php-scoper 0.18.11"
                    wget https://github.com/humbug/php-scoper/releases/download/0.18.11/php-scoper.phar -N --no-verbose

                    note "Running php-scoper"

                    # Work around possible PHP memory limits
                    php -d memory_limit=-1 php-scoper.phar add-prefix bin src vendor composer.json --config scoper.php --force --ansi --output-dir scoped-code

                    # the output code is in "/scoped-code", lets move it up
                    # the local directories have to be empty to move easily
                    rm -r bin src vendor composer.json stubs
                    mv scoped-code/* .

                    note "Dumping Composer Autoload"
                    composer dump-autoload --ansi --classmap-authoritative --no-dev

                    # make bin/ecs runnable without "php"
                    chmod 777 "bin/swiss-knife"
                    chmod 777 "bin/swiss-knife.php"

                    note "Finished"

            # copy PHP 7.4 composer + workflows
            -   run: cp -r build/target-repository/. .

            # clear the dev files
            -   run: rm -rf build prefix-code.sh scoper.php rector.php php-scoper.phar rector-local

            # setup git user
            -
                run: |
                    git config user.email "action@github.com"
                    git config user.name "GitHub Action"
            # publish to the same repository with a new tag
            # see https://tomasvotruba.com/blog/how-to-release-php-81-and-72-package-in-the-same-repository/
            -
                name: "Tag Downgraded Code"
                run: |
                    # separate a "git add" to add untracked (new) files too
                    git add --all
                    git commit -m "release PHP 7.2 downgraded"

                    # force push tag, so there is only 1 version
                    git tag "${GITHUB_REF#refs/tags/}" --force
                    git push origin "${GITHUB_REF#refs/tags/}" --force
